kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: ingress
  name: nginx
  namespace: ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 31080
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      nodePort: 31443
      protocol: TCP
      targetPort: 443
  selector:
    name: nginx-ingress-microk8s
