kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: redis
  name: redis-direct
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 31379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
